data:
  already_preprocessed: True
  batch_size: 256
  calc_stats: False
  data_dir: /usr/workspace/hip/eic/log10_Uniform_03-23/ECCE_HCAL_Files/hcal_pi+_log10continuous_1GeV-150GeV_10deg-30deg_07-21-23/
  num_procs: 64
  num_train_files: 200
  num_val_files: 46
  # num_test_files: 6
  output_dir: preprocessed_data/
  particle_type: pion
  preprocess: true
  shuffle: True
  num_features: 4
  k: 10
  hadronic_detector: hcal
  include_ecal: true
model:
  block_type: graphnet
  num_blocks: 1
  num_layers: 4
  latent_size: 64
  concat_input: true
  reducer: mean
  edge_block_opt:
    use_edges: true
    use_globals: true
    use_receiver_nodes: true
    use_sender_nodes: true
  global_block_opt:
    use_edges: false
    use_globals: true
    use_nodes: true
  node_block_opt:
    use_globals: true
    use_nodes: true
    use_received_edges: true
    use_sent_edges: false
training:
  epochs: 100
  learning_rate: 0.001
  save_dir: results/
