data:
  already_preprocessed: false
  batch_size: 256
  calc_stats: true
  condition_zsections: false
  data_dir: /home/xihe/eic-project/training_data_bak/
  hadronic_detector: hcal
  include_ecal: true
  k: 5
  n_zsections: null
  num_features: 4
  num_procs: 8
  num_test_files: 0
  num_train_files: 23
  num_val_files: 5
  output_dim: 4
  output_dir: /home/xihe/eic-project/processed_data/
  particle_type: pion
  preprocess: true
  shuffle: false
model:
  block_type: deepsets
  concat_input: true
  edge_block_opt:
    use_edges: true
    use_globals: true
    use_receiver_nodes: true
    use_sender_nodes: true
  global_block_opt:
    use_edges: false
    use_globals: true
    use_nodes: true
  latent_size: 128
  node_block_opt:
    use_globals: true
    use_nodes: true
    use_received_edges: true
    use_sent_edges: false
  num_blocks: 2
  num_layers: 4
  reducer: mean
training:
  epochs: 60
  learning_rate: 0.001
  save_dir: /home/xihe/eic-project/training_output/
