data:
  already_preprocessed: False # True while simulating all cases
  batch_size: 64
  calc_stats: True
  data_dir: ../training_data/
  num_procs: 1
  num_train_files: 6
  num_val_files: 2
  num_test_files: 0 #0
  output_dir: ../processed_data/
  particle_type: pion
  preprocess: true
  shuffle: false
  num_features: 4 # Energy, z,x,y.
  hadronic_detector: hcal #zdc_Fe
  k: 5  # 5,10
  n_zsections: Null
  condition_zsections: False
  include_ecal: True
  output_dim: 4
model:
  block_type: deepsets  #deepsets #graphnet
  concat_input: true
  edge_block_opt:
    use_edges: true
    use_globals: true
    use_receiver_nodes: true
    use_sender_nodes: true
  global_block_opt:
    use_edges: false
    use_globals: true
    use_nodes: true
  node_block_opt:
    use_globals: true
    use_nodes: true
    use_received_edges: true
    use_sent_edges: false # going out of the node , check get edges.
  num_blocks: 2 # 2,3,4
  num_layers: 4 # 2,3,4
  latent_size:  128 #,128,256
  reducer: mean
training:
  epochs: 60 # 10 epochs, 10 tr, 5 v and 5 ts
  learning_rate: 0.001
  save_dir: ../training_output/
